from typing import Any

def fetch_dashboard_json(grafana_url: str, dashboard_uid: str, api_key: str, verbose: bool = ...) -> dict[str, Any]: ...
def create_snapshot(grafana_url: str, dashboard_json: dict[str, Any], api_key: str, expires: int = ..., verbose: bool = ...) -> dict[str, Any]: ...
def save_snapshot_json(snapshot_json: dict[str, Any], path: str = ..., verbose: bool = ...) -> None: ...
def main() -> None: ...
